### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by sunbc0120** [3dmol/3Dmol.js#141]
Running "clean:build" (clean) task
Cleaning build...OK

Running "clean:doc" (clean) task

Running "concat:pre" (concat) task
File build/3Dmol-pre.js created.

Running "closure-compiler:$3Dmol" (closure-compiler) task
Warning: Command failed: /bin/sh -c java -jar "lib/closure_compiler/build/compiler.jar" --js "build/3Dmol-pre.js" --js_output_file "/Users/sunbaichuan/Documents/Github/3Dmol.js/build/3Dmol-min-pre.js" --compilation_level "SIMPLE_OPTIMIZATIONS" --warning_level "DEFAULT" --language_in "ECMASCRIPT5" --create_source_map "script.map"
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 Use --force to continue.

Aborted due to warnings.

**Comment by sunbc0120** [comment]
https://github.com/Homebrew/homebrew/issues/29610#issuecomment-47778002
