### ISSUE TITLE
py3Dmol install doesn't actually install anything

### ISSUE THREAD

**Issue by greglandrum** [3dmol/3Dmol.js#173]
For what it's worth, I'm using anaconda and python 3.5. My use of anaconda means that I've completely lost track of how stuff is supposed to work with pip, so I could very easily be doing something stupid.

Here's the initial attempt:
```
(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ python setup.py install
running install
running bdist_egg
running egg_info
creating py3Dmol.egg-info
writing dependency_links to py3Dmol.egg-info/dependency_links.txt
writing top-level names to py3Dmol.egg-info/top_level.txt
writing requirements to py3Dmol.egg-info/requires.txt
writing py3Dmol.egg-info/PKG-INFO
writing manifest file 'py3Dmol.egg-info/SOURCES.txt'
reading manifest file 'py3Dmol.egg-info/SOURCES.txt'
writing manifest file 'py3Dmol.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying py3Dmol.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py3Dmol.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py3Dmol.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py3Dmol.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py3Dmol.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/py3Dmol-0.5.1-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing py3Dmol-0.5.1-py3.5.egg
Copying py3Dmol-0.5.1-py3.5.egg to /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages
Adding py3Dmol 0.5.1 to easy-install.pth file

Installed /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages/py3Dmol-0.5.1-py3.5.egg
Processing dependencies for py3Dmol==0.5.1
Searching for idisplay
Reading https://pypi.python.org/simple/idisplay/
Best match: idisplay 0.1.2
Downloading https://pypi.python.org/packages/d3/fe/38acbdb022603fe98b066c5aaec353343a32c2a669100daa6542d3171f5e/idisplay-0.1.2.tar.gz#md5=981dca5d6887321d2acaec5fc2502eff
Processing idisplay-0.1.2.tar.gz
Writing /tmp/easy_install-893i8ktp/idisplay-0.1.2/setup.cfg
Running idisplay-0.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-893i8ktp/idisplay-0.1.2/egg-dist-tmp-8drgl_no
zip_safe flag not set; analyzing archive contents...
Moving idisplay-0.1.2-py3.5.egg to /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages
Adding idisplay 0.1.2 to easy-install.pth file

Installed /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages/idisplay-0.1.2-py3.5.egg
Searching for jupyter==1.0.0
Best match: jupyter 1.0.0
Adding jupyter 1.0.0 to easy-install.pth file

Using /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages
Searching for ipython==4.2.0
Best match: ipython 4.2.0
Adding ipython 4.2.0 to easy-install.pth file

Using /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages
Finished processing dependencies for py3Dmol==0.5.1



(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ ls -l /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages/py3D*
-rw-rw-r-- 1 glandrum glandrum 1795 Mai 10 18:16 /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages/py3Dmol-0.5.1-py3.5.egg

(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ pushd /tmp
/tmp ~/Code/3Dmol.js/py3Dmol ~/Code/3Dmol.js/py3Dmol /scratch/RDKit_git/Code/Profiling/GraphMol
(py3dmol)glandrum@Otter:/tmp$ python -c 'import py3Dmol'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'py3Dmol'
```

Ok, that failed. From looking around a bit, it seems like there may be a more modern way of doing this:

```
(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ python setup.py bdist_wheel
running bdist_wheel
running build
installing to build/bdist.linux-x86_64/wheel
running install
running install_egg_info
running egg_info
writing py3Dmol.egg-info/PKG-INFO
writing top-level names to py3Dmol.egg-info/top_level.txt
writing requirements to py3Dmol.egg-info/requires.txt
writing dependency_links to py3Dmol.egg-info/dependency_links.txt
reading manifest file 'py3Dmol.egg-info/SOURCES.txt'
writing manifest file 'py3Dmol.egg-info/SOURCES.txt'
Copying py3Dmol.egg-info to build/bdist.linux-x86_64/wheel/py3Dmol-0.5.1-py3.5.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/py3Dmol-0.5.1.dist-info/WHEEL


(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ pip install --no-index --find-links=./dist py3Dmol
Ignoring indexes: https://pypi.python.org/simple
Collecting py3Dmol
Requirement already satisfied (use --upgrade to upgrade): idisplay in /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages/idisplay-0.1.2-py3.5.egg (from py3Dmol)
Requirement already satisfied (use --upgrade to upgrade): jupyter in /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages (from py3Dmol)
Requirement already satisfied (use --upgrade to upgrade): ipython>=1.0 in /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages (from idisplay->py3Dmol)
Installing collected packages: py3Dmol
Successfully installed py3Dmol-0.5.1


(py3dmol)glandrum@Otter:/tmp$ python -c 'import py3Dmol'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'py3Dmol'

(py3dmol)glandrum@Otter:/tmp$ ls -l /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages | grep py3D
drwxrwxr-x  2 glandrum glandrum    4096 Mai 10 18:27 py3Dmol-0.5.1.dist-info

```

To make it work, I needed to manually copy in the py3Dmol directory:
```
(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ cp -r py3Dmol /home/glandrum/anaconda3/envs/py3dmol/lib/python3.5/site-packages
(py3dmol)glandrum@Otter:~/Code/3Dmol.js/py3Dmol$ pushd
/tmp ~/Code/3Dmol.js/py3Dmol ~/Code/3Dmol.js/py3Dmol /scratch/RDKit_git/Code/Profiling/GraphMol
(py3dmol)glandrum@Otter:/tmp$ python -c 'import py3Dmol'
(py3dmol)glandrum@Otter:/tmp$ 
```

**Comment by dkoes** [comment]
What if you do
`sudo pip3 install py3Dmol`
since you're using Python3?

**Comment by dkoes** [comment]
Gah, never mind.  It was my fault, I wasn't actually installing the package in setup.py (this is what I get for testing in the directory that has the package in it..).  
`pip install py3Dmol --upgrade`

**Comment by greglandrum** [comment]
Yep, that fixes it. Thanks!
