### ISSUE TITLE
Please add the pre-built js file 3Dmol-pre.js to the repository

### ISSUE THREAD

**Issue by yurivict** [3dmol/3Dmol.js#417]
I followed your build instructions, but they aren't sufficient.
First, ```grant-cli``` complains that it also needs ```grant``` to be installed, so ```npm install grunt``` also needs to be run. Then it complains that these modules need to be installed: ```grunt-contrib-clean grunt-contrib-concat grunt-contrib-uglify grunt-closure-compiler grunt-shell grunt-node-inspector grunt-contrib-copy```. Then it crashes:
```
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-freebsd-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-freebsd-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/usr/local/bin/python2", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:149:21)
gyp ERR! System FreeBSD 12.0-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/home/yuri/science-calculations/ChemWiz1/3Dmol.js/node_modules/v8-debug/build/debug/v1.0.1/node-v72-freebsd-x64/debug.node" "--module_name=debug" "--module_path=/usr/home/yuri/science-calculations/ChemWiz1/3Dmol.js/node_modules/v8-debug/build/debug/v1.0.1/node-v72-freebsd-x64" "--python=/usr/local/bin/python2"
gyp ERR! cwd /usr/home/yuri/science-calculations/ChemWiz1/3Dmol.js/node_modules/v8-debug
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/usr/local/bin/python2", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:149:21)
gyp ERR! System FreeBSD 12.0-STABLE
gyp ERR!node-pre-gyp  command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr
```

Node probably woks well only on linux, but fails on FreeBSD.

Could you please just add ```3Dmol-pre.js``` so that people won't need to build it, because it's just one text file.

**Comment by dkoes** [comment]
3Dmol-pre.js is a temporary file that is deleted before the conclusion of the build.

What is it that you want it for?

**Comment by yurivict** [comment]
I wanted to see how it works, but the build fails.

**Comment by dkoes** [comment]
How what works?  Like I said, 3dmol-pre is a temporary file.  You can download built versions of the latest releases form cloudfare or the latest built version from http://3Dmol.csb.pitt.edu/build/3Dmol.js as described in the documentation:
http://3dmol.csb.pitt.edu/doc/index.html

**Comment by yurivict** [comment]
I see, thanks!
